import type { Metadata } from "next";
import { Cormorant, Geist, Geist_Mono, Playfair } from "next/font/google";
import "./globals.css";
import ResponsiveNavBar from "./components/Home/NavBar/ResponsiveNavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorant = Cormorant({
  weight: ["300", "400", "500", "600", "700"]
})

const playFair = Playfair({
  weight: ["300", "400", "500", "600", "700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cormorant.className} antialiased`}
      >
        <ResponsiveNavBar />
        {children}
      </body>
    </html>
  );
}
